### ISSUE TITLE
Notifications cut of in combination with drop down script

### ISSUE THREAD

**Issue by ShalokShalom** [StylishThemes/GitHub-Dark-Script#37] opened 2017-06-30 08:01 UTC
![screenshot_20170630_095342](https://user-images.githubusercontent.com/6344099/27726475-f07f714e-5d7a-11e7-8d1e-4b78aa764481.png)

As you can see, cut an issue the names of the issues here.

This happens only, when i use that script here together in combination with GithubDarkScript.
https://openuserjs.org/scripts/joeytwiddle/Github_Notifications_Dropdown

**Comment by Mottie** [comment] 2017-06-30 11:43
Hi @ShalokShalom!

That appears to be extra CSS added by the userscript author - see [lines 106-108 here](https://openuserjs.org/scripts/joeytwiddle/Github_Notifications_Dropdown/source):


```js
	  +" .notifications-dropdown > .css-truncate, .notifications .list-group-item-name a { " +
  "   max-width: 200px !important;" +
  " } ";
```

We *could* add a definition to [GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark) to override this entry, but it would better to contact the author and have it fixed instead. 

I did not find the userscript hosted anywhere publicly, so we can ping @joeytwiddle, or leave a message for him on [OUJS](https://openuserjs.org/users/joeytwiddle/comments) about this issue.

**Comment by Mottie** [comment] 2017-06-30 11:49
Ahhh, I found it's home... deep in a sub-directory: https://github.com/joeytwiddle/code/blob/master/other/gm_scripts/github_notifications_dropdown/github_notifications_dropdown.user.js

**Comment by silverwind** [comment] 2017-06-30 13:11
Hmm, I cannot reproduce, but this looks like something better fixed in that script. Does changing the loading order of scripts change anything for you? (if your engine supports it)

<img width="574" src="https://user-images.githubusercontent.com/115237/27736877-4a80a49e-5da6-11e7-9c54-af1f217dd3cc.png">

**Comment by ShalokShalom** [comment] 2017-06-30 13:42
I can reproduce on Greasemonkey in Firefox and Violentmonkey on Opera, both cannot change the order.
What do you use?

**Comment by silverwind** [comment] 2017-06-30 13:51
Greasemonkey on Firefox can do that.

**Comment by ShalokShalom** [comment] 2017-06-30 14:42
Nope, its the same then..

To be precise: It happens only once i actually **call** the dropdown script.

**Comment by Mottie** [comment] 2017-07-05 03:02
> Hmm, I cannot reproduce

I think you'll see it when you look at the [all notifications view](https://github.com/notifications?all=1), *then* open the notification popup.

**Comment by silverwind** [comment] 2017-07-05 15:54
Ah, I see. It does happen without GitHub Dark enabled, so I don't see why we should attempt to solve it on our side. This should be fixed in the Notification Dropdown script.

**Closed as completed by silverwind** 2017-07-05 15:54 UTC
Labels: question :grey_question:

**Comment by ShalokShalom** [comment] 2017-07-06 09:56
@Mottie This is one way, yes.

**Comment by joeytwiddle** [comment] 2017-07-13 07:30
Fixed in 0.9.8, probably. Maybe broken even more. But probably fixed, hopefully. Or maybe not.

OK I checked, it's fixed. Probably.

**Comment by ShalokShalom** [comment] 2017-07-13 16:53
I removed the lines, which Mottie gave me and that resulted in the effect, that the text went over each other, lapping. Is this fixed too? By making it wider?

**Comment by Mottie** [comment] 2017-07-14 00:55
> the text went over each other, lapping

Please share a screenshot of what you're describing... I'm not sure what you mean.

**Comment by ShalokShalom** [comment] 2017-07-14 07:22
![screenshot_20170714_092129](https://user-images.githubusercontent.com/6344099/28202490-e3c9c4b2-6875-11e7-9014-8dd1acf3e5b0.png)

Because they are not wide enough.

**Comment by ShalokShalom** [comment] 2017-07-15 17:14
@joeytwiddle I updated to your version, now i get dots:

![screenshot_20170715_191339](https://user-images.githubusercontent.com/6344099/28241276-bf51cf36-6991-11e7-98a2-cd4d9b851a00.png)

I want a wider notification drop down, there is no reason to make it that small for me :)

**Comment by joeytwiddle** [comment] 2018-05-03 03:35
Apologies for the delay, I was making a cup of tea.

I agree it's too narrow. On July 24th 2017, in version 0.9.9, I expanded the minimum width from 500px to 700px. I hope you like it better now!

By the way you might like the [Wide Github](https://openuserjs.org/scripts/xthexder/Wide_Github) script too. Or [my fork](https://openuserjs.org/scripts/xthexder/Wide_Github) which increases Github's width to 1500px but no more.

**Comment by ShalokShalom** [comment] 2018-05-03 03:38
I think we had a conversation somewhere else, yes thanks (still too narrow for me, I am on standard Github again)
